name: Deploy

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  cron:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Call Deploy Hook
        env:
          STAGE: staging
        run: curl ${{ secrets.NINJA_DEPLOY_HOOK }}
